elm/compiler

README.md

Nice and simple.  Not really much more to say!

fix install script url

---

src/Elm/Utils.hs

To improve user experience in a situation like this: https://github.com/kevva/elm-bin/issues/13.

Explain path to set ELM_HOME to after npm install

---

elm-compiler.cabal

Add wl-pprint to test dependencies.

---

src/Elm/Package.hs

Restrict the set of valid package names

---

src/Elm/Compiler/Type.hs

Should fix https://github.com/elm-lang/elm-compiler/issues/1072.

Fix pretty-printing bug concerning unit type

---

src/Nitpick/PatternMatches.hs
src/Reporting/Error/Pattern.hs

Improve error messages for incomplete patterns in args and let-bindings

---

src/Reporting/Error/Pattern.hs
src/Reporting/Error/Type.hs
src/Type/Solve.hs
src/Type/Type.hs

Need to add some sort of tests for #983, #956, and #707
The problem is that if there is a regression, things will diverge. So somehow the tests need to not do that I think. Not sure how.

Fix infinite type issues

---

src/Reporting/Error/Type.hs

Fix https://github.com/elm-lang/error-message-catalog/issues/46

Provide nicer message when trying to use a non-function as a function

---

src/Reporting/Error/Syntax.hs
src/Reporting/Render/Type.hs

Fix #1171 for the greater good

Stop using … because of dumb British windows

---

src/Elm/Package.hs

Do not allow upper case letters in new project names

---

changelog.md

https://github.com/elm-lang/elm-compiler/issues/1191#issuecomment-160890566

Update changelog for 0.16

---

src/Generate/JavaScript/Expression.hs
tests/test-files/good-expected-js/CodeGenBugs/TailRecursion_NameNormalization.elm.js
tests/test-files/good/CodeGenBugs/TailRecursion_NameNormalization.elm

Should fix https://github.com/elm-lang/error-message-catalog/issues/77 and https://github.com/elm-lang/elm-compiler/issues/1226, and let test case https://github.com/elm-lang/elm-compiler/pull/1250 succeed.

Add name normalization in tail optimization code

---

hints/recursive-alias.md
src/Reporting/Error/Helpers.hs

This reverts commit 1a228b19494774731df6d3e41377fb3d4cbde934.

Bring in minor changes

---

.github/ISSUE_TEMPLATE.md

The hope is that this will tremendously cut down on duplicates being opened.

In issue template, direct to "meta" issues

---

.github/ISSUE_TEMPLATE.md

As per https://github.com/elm-lang/elm-compiler/issues/1457#issuecomment-238225280.

Add #1240 to issue template

---

hints/recursive-alias.md

Trying to help making elm documentation even better.

Minor grammatical fix

---

hints/import-cycles.md

Just reading through the stuff that is to come in 0.19. Whenever I see something that can be slightly improved I will try to help.

Minor grammatical fixes

---

docs/elm.json/package.md

Package readme: Minor syntactic fix

---

upgrade-docs/0.19.md

I couldn't find any docs for this change.

Added missing upgrade doc for (,)

---

hints/optimize.md

Fixed wrong argument given to Uglifyjs in [hints/optimize](https://github.com/elm/compiler/blob/master/hints/optimize.md). See issue #2162.

Fixed Uglifyjs Command

---

.github/workflows/set-issue-expectations.yml

I believe there was a word missing before.

Fix typo in issue template

---

.github/CONTRIBUTING.md

**Quick Summary:** This file is out of date, so I am trying to merge in the "inbound=outbound" info with the PR expectations that the robot gives.
I am also testing that the recent robot config changes make a comment appear on this PR.

update CONTRIBUTING.md for latest practices

---

.github/workflows/set-pull-expectations.yml

There is now a DISCLAIMER at https://github.com/thollander/actions-comment-pull-request that says this can be done as a [GitHub script](https://github.com/actions/github-script).

try to fix markdown format for robo-PR-comments
