elm/compiler

elm-compiler.cabal, tests/Test/Compiler.hs, tests/Test/Property.hs
In particular, this PR accomodates the following changes to Compiler.compile:
* New parameter isRoot :: Bool (introduced in [fb1a6d26f0](https://github.com/elm-lang/elm-compiler/blob/fb1a6d26f09f3e43fc45df9df82ec548bbb276e7/src/Elm/Compiler.hs))
* Return value of type `([Warning], Either [Error] (PublicModule.Interface, String))`, rather than `Either String (PublicModule.Interface, String)`.
Note: This fixes `Test.Compiler`, but not `Test.Property`.  I got the tests to run by:
1. Removing `Test.Property` and `Test.Property.Arbitrary` from elm-compiler.cabal.
2. Removing `import Test.Property` and the reference to `propertyTests` in [`Test.hs`](https://github.com/manleyjster/elm-compiler/blob/fix-compiler-tests/tests/Test.hs#L13).
Running `cabal test` then results in all of the tests …
=> Update helper functions in Test.Compiler to fit new version of Compiler.compile.

src/Reporting/Error/Syntax.hs
**Before:** COMPILER IS ANGRY AT YOU :angry: 
```
Naming multiple values 'dropZone' in a single let-expression makes
things ambiguous. When you say 'dropZone' which one do you want?!
39|           dropZone = makeSection' True (" ", [])
^^^^^^^^
Find all the values named 'dropZone' in this let-expression and
do some renaming. Make sure the names are distinct!
```
**After:** Compiler is here to help :smile: 
```
Naming multiple values 'dropZone' in a single let-expression makes
things ambiguous. When you say 'dropZone' which one do you want?
39|           dropZone = makeSection' True (" ", [])
^^^^^^^^
Find all the values named 'dropZone' in this let-expression and
do some renaming. Make sure the names are distinct!
```
=> Replace "want?!" with "want?"

src/Reporting/Error/Canonicalize.hs
**Before:**
```
Type Shrink.Shrinker has too fewarguments.
```
**After:**
```
Type Shrink.Shrinker has too few arguments.
```
=> Fix a missing space

src/Parse/Helpers.hs, src/Parse/Module.hs
Previously, e.g., on a parse error for a record label, the parser would complain it expected a `lower case variable`, which might confuse the programmer. (Why is a record label a "variable"? It should be a "name".) Similarly, in the parse error for `case ... of Module.lowercasename -> ...` the parser would complain it expected an `upper case variable`, which again is confusing (see https://github.com/elm-lang/elm-compiler/issues/948). Instead, it would make more sense to complain that an `upper case name` was expected (a constructor is not a "variable", but it is a "name").
=> Improved parse error messages

src/CommandLineRouter.hs, src/Elm/Utils.hs, src/Generate/Cases.hs, src/Generate/JavaScript/Port.hs, src/Parse/Helpers.hs, src/Parse/Module.hs, src/Reporting/Error/Canonicalize.hs, src/Reporting/Error/Syntax.hs, src/Reporting/Error/Type.hs, src/Reporting/Warning.hs, src/Type/Environment.hs, src/Type/Solve.hs, src/Type/Unify.hs
The motivation behind this PR was that I ran into this error:
```
Could not find variable 'makeSection''.
Close matches include:
makeSection
```
At first I ran off to figure out why `makeSection` was not in scope, then eventually came back and realized it was actually complaining about a variable called `makeSection'`. I missed it because of the single quotes around the variable name.
This PR changes such usages to backticks instead, like so:
```
Could not find variable `makeSection'`.
Close matches include:
makeSection
```
Arguments for this change:
* Single quotes are often used at the end of variable names, so the current collision will come up often.
* Backticks are not allowed in variable names, so there is no potential for such a collision there.
* Backticks are used in Markdown to …
=> Use backticks instead of single quotes for reporting code terms

src/Reporting/Error/Type.hs
**Before:**
```
As I infer the type of values flowing through your program
```
**After:** (`s/type/types`)
```
As I infer the types of values flowing through your program
```
=> Minor grammatical fix

elm-compiler.cabal
Are there specific reasons that `blaze-html` was constrained to `< 0.8` and `blaze-markup` to `< 0.7`?
These are the only constraints that currently keep this repository from building with the set of constraints given by "Long Term Support Haskell 3.1": https://www.stackage.org/lts-3.1/cabal.config
=> Relax bounds on blaze-... libraries

bench/CompilerBenchmarks.elm, bench/elm-package.json, bench/src/AnimateBench.elm, bench/src/ArrayBench.elm, bench/src/Benchmark.elm, bench/src/CtorBench.elm, bench/src/DictBench.elm, bench/src/IfBench.elm, bench/src/LargeDictionary.elm, bench/src/ListBench.elm, bench/src/Native/Benchmark.js, bench/src/Native/BenchmarkJS.js, bench/src/PatternMatchBench.elm, bench/src/RecordBench.elm, bench/src/SmallCtorBench.elm, bench/src/SmallRecordBench.elm, bench/src/SmallTupleBench.elm, bench/src/TodoBench.elm, bench/src/TupleBench.elm
Add a benchmark suite to elm-compiler.
To test a particular elm version, just do
`elm make CompilerBenchmarks.elm --output=Benchmark.html` with whatever version of Elm you are testing, then load the resulting Html page in your browser.
=> Add benchmarks to elm-compiler

elm-compiler.cabal
`stack` could not resolve the needed build artifacts without adding `elm-compiler` as a dependency to the corresponding executable. Additionally, this bumps the upper bounds on `blaze-html` and `blaze-markup` and adds `Paths_elm_compiler` to `other-modules` in order to silence a warning from `stack`.
=> Fixes cabal file to work with stack

elm-compiler.cabal, src/AST/Module.hs, src/CommandLineRouter.hs, src/Compile.hs, src/Elm/Compiler.hs, src/Elm/Compiler/Version.hs, src/Elm/Docs.hs, src/Elm/Package.hs, src/Elm/Utils.hs, tests/Test/Compiler.hs
SEE ALSO: related PRs for [elm-make](https://github.com/elm-lang/elm-make/pull/52) and [elm-package](https://github.com/elm-lang/elm-package/pull/127)
Refactors so that the `Name` type is in elm-compiler, so that we can pass Package names around the compiler process.
We create a new module, `Elm.Package`, containing the `Name` and `Version` types for packages.
`toString :: Version -> String` was renamed `verstionToString`, to avoid conflicts with `toString :: Name -> String`. Similarly with `fromString`.
We've moved the `elm :: Version` from Elm.Package.Version to Elm.Compiler, and renamed it to `version :: Version`.
=> Common package module (take 2)

bench/src/IfBench.elm, src/AST/Module.hs, src/Compile.hs, src/Elm/Compiler.hs, src/Elm/Compiler/Module.hs, src/Elm/Package.hs, src/Type/Inference.hs, tests/Test/Compiler.hs
SEE ALSO: [PR in elm-make](https://github.com/elm-lang/elm-make/pull/53).
NOTE: this appears to build things well, but it's hard to test because Core is currently broken (multi-way ifs and record updates).
This makes the changes necessary so that, when two packages have hidden modules with the same name, problems don't arise.
The ModuleNames we receive from Elm-make are now qualified by package name, and version. We also receive a dictionary mapping module names to package names for each imported package, so we know which interface files to give `Canonicalize.module'`. This dictionary has been added to the `Elm.Compiler.Context` type.
In Elm.Compiler.Module, we've added the `CanonicalName` type, which qualifies module names by package name and version. A similar type is in AST.Module, …
=> Avoid name conflicts

src/AST/Expression/Canonical.hs, src/AST/Expression/Optimized.hs, src/AST/Variable.hs, src/Canonicalize.hs, src/Canonicalize/Declaration.hs, src/Canonicalize/Sort.hs, src/Docs/Centralize.hs, src/Nitpick/PatternMatches.hs, src/Optimize/TailCalls.hs, src/Type/Constrain/Expression.hs
Adds annotations containing the referenced top-levels and imported variables for each Definition in a module.
=> Add Facts to Canonical.Def

tests/Test/Compiler.hs
Right now Generate/JavaScript.hs has a lot of errors. So if you run:
`ELM_WRITE_NEW_EXPECTED=1 cabal test`
It will write empty files for all the examples with errors.
But there are several other test cases which do compile and do need to be updated, and you don't want to have to pick through which ones to commit.
@evancz
=> Test fix empty expected files

elm-compiler.cabal
Remove unused package dependencies from `elm-compiler.cabal`. These were detected using HVR's [`packunused`](https://hackage.haskell.org/package/packunused) utility. This should hopefully reduce build times and slightly reduce incidences of "Cabal hell" in the future.
This PR also removes the elm-compiler dependency from the elm executable as the bug in stack requiring this change has been fixed and a new version of stack released. I kept it in a separate commit in case you want to cherry pick.
=> Remove unused package dependencies

src/Elm/Utils.hs, src/Type/State.hs
This allows the elm-compiler source code to be properly parsed by haskell-src-exts.  (This allows, for instance, elm-compiler to be processed by [SourceGraph](https://hackage.haskell.org/package/SourceGraph))
For background: GHC has a bug that allows successful compilation without the MultiParamTypeClasses pragma, but such files are "not valid standard haskell".  See https://github.com/haskell-suite/haskell-src-exts/issues/29
=> Add MultiParamTypeClasses pragma where appropriate

hints/recursive-alias.md, hints/type-annotations.md, src/Reporting/Error/Canonicalize.hs, src/Reporting/Error/Type.hs, src/Type/Constrain/Expression.hs
Always call things “user-defined type variables” instead of “rigid type
variables”
Try to be more non-specific in the case of a rigid/rigid clash, just
link out to hint documentation.
=> Merge in online hints for annotations and recursive aliases

src/Reporting/Error/Helpers.hs
Seems like unicode makes it go crazy pretty reliably
=> Stop using ↓ because of dumb British windows

src/Elm/Package.hs
Instead it makes sense to make package.elm-lang.org disallow publishing
of packages with capital letters. This way things keep working for 0.15
people.
=> Allow upper case names for now

src/Elm/Utils.hs, src/Reporting/Report.hs
cc @jvoigtlaender
I thought that displayIO was for ANSI and displayS was for not-ANSI. It
turns out that displayS will add the ANSI codes into the string if you
are on not-Windows. This meant that garbage characters were ending up
in the output of JSON errors or reactor errors
@rtfeldman, I’ll try to get a new set of binaries ready for linux
32-bit and mac
=> Fix ANSI issue everywhere

src/Parse/Helpers.hs, src/Reporting/Error/Syntax.hs
Given this file:
```elm
list =
<tab>[
<tab><tab>1
<tab>]
```
Elm will now give this error message:
```
-- SYNTAX PROBLEM -------------------------- TabIndent.elm
A tab character was found, but all whitespace (including indentation) must be
spaces not tabs.
3│ 	[
^
I am looking for one of the following things:
whitespace
```
=> Add custom error message if tab character is found in parsing.

CONTRIBUTING.md, elm-compiler.cabal, src/CommandLineRouter.hs
Fix #1384, thanks to @lorenzo!
=> Update link to JS style guide

src/Reporting/Error/Canonicalize.hs
This addresses https://github.com/elm-lang/error-message-catalog/issues/129 by framing the error in terms of how to fix it.
```
-- NAMING ERROR ------------------------------------------------------- form.elm
Cannot find variable `String.length`.
16|         if model.password == "" || String.length model.password < 8 then
^^^^^^^^^^^^^
The qualifier `String` is not in scope. 
Detected errors in 1 module.   
```
```
-- NAMING ERROR ------------------------------------------------------- form.elm
Cannot find variable `String.length`.
16|         if model.password == "" || String.length model.password < 8 then
^^^^^^^^^^^^^
No module called `String` has been imported.
Detected errors in 1 module.   
```
=> Express unknown qualifier in terms of modules

hints/missing-patterns.md
The corresponding issues (elm-lang/core#216 and elm-lang/core#215) have been
closed.
=> Remove references to `(?)` and `unsafe` in missing patterns hints

src/Reporting/Error/Canonicalize.hs
On the mailing list, [someone used a wrong port type and got this error](https://groups.google.com/forum/#!topic/elm-discuss/3ieqkWBPvaE):
```
8| port graphName : String
^^^^^^^^^^^^^^^^^^^^^^^
You are saying it should be:
String
But you need to use the particular format described here:
<http://guide.elm-lang.org/effect_managers/>
```
However, the link http://guide.elm-lang.org/effect_managers/ doesn't describe any particular port type format. The link http://guide.elm-lang.org/interop/javascript.html does.
=> Fix wrong link in port type error

src/Nitpick/Pattern.hs, src/Nitpick/PatternMatches.hs, src/Reporting/Error/Pattern.hs
Results in 5x faster builds on our app.
Successive patterns on data constructors like tuples can cause the list
of unhandled patterns to grow exponentially.
This commit de-duplicates entries in the unhandled patterns list. This
tames the exponential growth considerably.
The proper solution is to create a real union type for nitpicking
patterns. There’s still quite a bit of speed improvement available.
Build times (app: [Sketch-n-Sketch](https://ravichugh.github.io/sketch-n-sketch/releases/index.html)):
```
Elm 0.16:                                  2:32.4
Elm 0.16 with this commit:                 0:27.8
Elm 0.16 with no exhaustiveness checking:  0:11.3
```
This PR should solve #1267, but closer to the source.
This may or may not affect #1362.
cc @ravichugh
=> Speed up exhaustiveness checker

src/Reporting/Error/Canonicalize.hs
Adds `#ports` to the end of the URL in the hint about ports.
https://guide.elm-lang.org/interop/javascript.html#ports takes you straight to the part of the page that explains the format.
**Error message before:**
```
But you need to use the particular format described here:
https://guide.elm-lang.org/interop/javascript.html
```
**Error message after:**
```
But you need to use the particular format described here:
https://guide.elm-lang.org/interop/javascript.html#ports
```
=> Link directly to #ports section for ports hint

src/Parse/Binop.hs
Fixes typo see [error-message-catalog issue 176](https://github.com/elm-lang/error-message-catalog/issues/176)
=> Fixes typo in fail message: singe -> single

hints/imports.md
These are simple typos or omissions in the documentation.
=> Fix a few typos in the imports hint

hints/port-modules.md
Fixed small typo in hints markdown file.
=> Port-modules: Typo "thes" fixed

ui/browser/assets/styles.css
I believe this fixes a style in reactor like this.
Before:
After:
Another plan would be adding `overflow: hidden;` (or scroll, auto ...) to `.box`.
```css
.box {
border: 1px solid #c7c7c7;
border-radius: 5px;
margin-bottom: 40px;
+    overflow: hidden;
}
```
=> Fix corner style of boxes in reactor

installers/npm/bin/elm, installers/npm/package.json
currently published as `elm@rc3` if you'd like to try it.
=> final working version of Elm npm installer

upgrade-docs/0.19.md
=> Fix a couple of links to the docs

upgrade-docs/0.19.md
`(!) : model -> List (Cmd msg) -> ( model, Cmd msg )` was removed from core. This change mentions the removal in the upgrade document for 0.19.
https://package.elm-lang.org/packages/elm-lang/core/latest/Platform-Cmd#(!)
=> Add removal of bang operator (!) to upgrade doc

installers/README.md
I was passing through and noticed some incomplete markdown links. I assumed that they were still intended to be links and added back the references from a previous commit.
Thanks!
=> Fix markdown links in installation instructions.

builder/src/Reporting/Exit.hs
Fixed a typo.
P.S. The contributor agreement link at [CONTRIBUTING.md](https://github.com/elm/compiler/blob/master/.github/CONTRIBUTING.md) is broken.
=> Typo in Exit.hs

hints/bad-recursion.md, hints/comparing-custom-types.md, hints/comparing-records.md, hints/implicit-casts.md, hints/import-cycles.md, hints/recursive-alias.md, hints/type-annotations.md
I have been through the documents in the `hints/` folder, and I found a few typos/errors and one broken link.
NA
I noticed a missing word in the [bad-recursion](https://github.com/elm/compiler/blob/master/hints/bad-recursion.md) but I wasn't sure how to fix, and therefore refrained to do so in the PR. In the following sentence, I think that there is a missing word where I added *FOR*
> A common case is a JSON decoder *FOR* a discussion forums where a comment may have replies, which may have replies, which may have replies, etc.
Let me know if you wish for me to change anything or to take a look at something else.
=> Typo fixing in the hint documents

builder/src/Reporting/Exit.hs
Hej Evan!
There are references to a dependency management tool in `elm reactor` which does not yet exist. This PR removes them.
Kh.
=> Remove references to dependency management tool

.gitignore, .travis.yml, installers/linux/Dockerfile
* Linux binary released only on master tags
* emails sent only on status change (and only to myself for now)
* split-sections added to GHC options
* updated to Alpine 3.11 with ghc 8.6.5
=> add Travis CI Linux x86_64 build and tags releases

installers/linux/Dockerfile
Sorry, missed that in previous PR (this has no functional impact, it's just cleaner because there was a slash for 3 directories, but not the 4th one, which was unintentional but looked like it was).
=> remove unneeded slash characters from Dockerfile

docs/elm.json/package.md
Context: I used to link to the "Preparing for Publication" section in the `elm-package` repo that recommended BSD-3 for package licenses.
> The recommended `license` is BSD3, but of course, you can use whatever license you want.
[It was removed](https://github.com/elm-lang/elm-package/commit/2076638d812d9dea641e6e695951495f523bb98f#diff-04c6e90faac2675aa89e2176d2eec7d8) when the `elm-publish` functionality was moved to the core repo. This change will allow me to point to a definitive source that says that BSD-3 is the recommended default in the Elm ecosystem.
See https://github.com/dillonkearns/idiomatic-elm-package-guide/issues/3
=> Clarify BSD-3 is recommended license for packages.

installers/npm/download.js
**Quick Summary:**
Allow M1 users to continue to install via npm and use the `x64:64-bit` binary (via rosetta) until we get a native build.
I would like to continue to allow people with M1 macs to install and use Elm through the npm package, and I think this is a decent stop-gap until we can get a native build. Right now the install fails trying to install a url that does not exist (because the darwin/arm64 combo is not covered), this falls back to the `x64:64-bit` binary download and lets them use Rosetta.
This isn't a problem anywhere else, because the other methods of installation are direct binary downloads, so it asks the user to either install Rosetta or uses Rosetta directly, we just need to make sure we allow them to still get the binary.
Thanks!
=> Allow M1 users to continue to install elm via our npm package

hints/implicit-casts.md
**Quick Summary:**
Remove an insufficiently-supported assertion about the Ruby language.
The page on [Implicit Casts](/elm/compiler/blob/c4a81fcde7efe9199c0037d1810c08b32ebb7d08/hints/implicit-casts.md) says;
> Many languages automatically convert from Int to Float when they think it is necessary. This conversion is often called an implicit cast. Languages that will add in implicit casts for addition include...Ruby...These languages generally agree that an Int may be implicitly cast to a Float when necessary.
> Note: Ruby does not follow the trend. They implicitly cast a Float to an Int, truncating all the decimal points!
Since Ruby is mentioned as an exception, I assume the author had an example in mind.
I haven't been able to think of one. Vaguely close is the fact that `5 / 6` produces …
=> Remove claim about the Ruby language

compiler/src/Reporting/Error/Pattern.hs
Fix typo in word `possiblities` -> `possibilities`.
=> fix: typo This pattern does not cover all possiblities

.github/workflows/set-pull-expectations.yml
This should hopefully fix the comment not showing up on pull requests.
It needs testing.
That being said, I would like you to consider not doing it like this, but using githubs contributions feature, it quiet a bit better to me. 
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
=> Fix pull request expectations not getting posted

.github/CONTRIBUTING.md, compiler/src/Reporting/Error/Syntax.hs
**Quick Summary:**
I encountered this error message when playing around in elm repl. I had to re-read the sentence a couple times to make sure I understood what the compiler was telling me. I hope this small change makes the message just a little easier to understand 😄
I also updated the link to the ContributorAgreement as I encountered a 404 when I decided to submit this change. Let me know if you'd like that to be in a separate pull request 🙂
=> Personalize MISSING EXPRESSION message
